name: Bug Report
description: Report a reproducible bug with clear validation details.
title: "[Bug] "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug. Please include enough detail for someone else to reproduce this on the first pass.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is wrong?
      placeholder: Concise description of the observed bug.
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How bad is the impact?
      options:
        - "S1 - Critical (crash, data loss, release blocker)"
        - "S2 - High (major feature broken)"
        - "S3 - Medium (workaround exists)"
        - "S4 - Low (minor issue)"
    validations:
      required: true
  - type: dropdown
    id: regression
    attributes:
      label: Regression
      description: Did this work in a previous build?
      options:
        - "Yes"
        - "No"
        - "Unknown"
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      description: Which part of the project is impacted most?
      options:
        - "UI/UX"
        - "Authentication"
        - "Networking/API"
        - "Persistence/Data"
        - "Build/CI"
        - "Other"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction Steps
      description: Provide deterministic steps so an agent can reproduce.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What happened instead?
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Impact And Scope
      description: Which areas are affected (feature, files, severity)?
      placeholder: "Example: Settings screen only, regression from commit <sha>, blocks release."
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Include app version, device/simulator, iOS version, and Xcode version.
      placeholder: Hadge x.y.z, iPhone 15 simulator, iOS 18.2, Xcode 16.x
    validations:
      required: true
  - type: textarea
    id: evidence
    attributes:
      label: Logs Or Evidence
      description: Paste logs, screenshots, or links that confirm the issue.
    validations:
      required: false
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-Submission Checklist
      options:
        - label: I searched existing issues for duplicates.
          required: true
        - label: I can still reproduce this on the latest main branch build.
          required: true
