name: Feature Request
description: Propose an enhancement with clear acceptance criteria.
title: "[Feature] "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Please focus on user value and testable outcomes. This helps keep implementation scoped and reviewable.
  - type: dropdown
    id: request_type
    attributes:
      label: Request Type
      options:
        - New capability
        - Improvement to existing behavior
        - Developer experience / tooling
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What user or developer problem are we solving?
      placeholder: Describe the current pain point.
    validations:
      required: true
  - type: textarea
    id: users
    attributes:
      label: Who Benefits
      description: Which users or contributors are affected, and how often?
      placeholder: "Example: New contributors setting up the repo for the first time."
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: What should be built?
      placeholder: Describe expected behavior and UX.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other options were considered and why not choose them?
    validations:
      required: false
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: List testable outcomes so agents can implement and verify.
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true
  - type: textarea
    id: success_metrics
    attributes:
      label: Success Signals
      description: How will we know this request succeeded?
      placeholder: "Example: Fewer setup-related support issues and faster first build time."
    validations:
      required: true
  - type: textarea
    id: constraints
    attributes:
      label: Constraints
      description: Security, performance, compatibility, or timeline constraints.
    validations:
      required: false
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-Submission Checklist
      options:
        - label: I searched existing issues for similar requests.
          required: true
        - label: I included measurable acceptance criteria.
          required: true
