name: Feature Request
description: Propose an enhancement with clear acceptance criteria.
title: "[Feature] "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What user or developer problem are we solving?
      placeholder: Describe the current pain point.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: What should be built?
      placeholder: Describe expected behavior and UX.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other options were considered and why not choose them?
    validations:
      required: false
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: List testable outcomes so agents can implement and verify.
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true
  - type: textarea
    id: constraints
    attributes:
      label: Constraints
      description: Security, performance, compatibility, or timeline constraints.
    validations:
      required: false
